curl 'http://pushkin-lab.ru:8889/analyze' \
  -H 'Connection: keep-alive' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Origin: http://localhost:8888' \
  -H 'Referer: http://localhost:8888/' \
  -H 'Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7' \
  --data-binary '{"text":"Минобороны Азербайджана впервые опубликовало данные о военных потерях в ходе конфликта в Карабахе.\n\nПо информации ведомства, погибли 2783 военнослужащих. Еще более ста считаются пропавшими без вести. В госпиталях находятся 1245 военных.","mode":"foreign"}' \
  --compressed

#####
curl 'http://localhost:8889/analyze' \
  -H 'Connection: keep-alive' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Origin: http://localhost:8888' \
  -H 'Referer: http://localhost:8888/' \
  -H 'Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7' \
  --data-binary '{"text":"Минобороны Азербайджана впервые опубликовало данные о военных потерях в ходе конфликта в Карабахе.\n\nПо информации ведомства, погибли 2783 военнослужащих. Еще более ста считаются пропавшими без вести. В госпиталях находятся 1245 военных.","mode":"native"}' \
  --compressed

#####
  curl 'http://localhost:8889/analyze' \
  -H 'Connection: keep-alive' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Origin: http://localhost:8888' \
  -H 'Referer: http://localhost:8888/' \
  -H 'Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7' \
  --data-binary '{"text":"Минобороны Азербайджана впервые опубликовало данные о военных потерях в ходе конфликта в Карабахе.\n\nПо информации ведомства, погибли 2783 военнослужащих. Еще более ста считаются пропавшими без вести. В госпиталях находятся 1245 военных.","mode":"foreign"}' \
  --compressed