version: "3"
services:
  frontend:
    image: 1eshkin/textometr-frontend
    ports:
      - "8888:80"
  backend:
    image: 1eshkin/textometr-backend
    environment:
      - MAX_WORKERS=1
    ports:
      - "8889:80"
    deploy:
      resources:
        limits:
          memory: 1000M