version: "3"

services:
  frontend:
    image: 1eshkin/textometr-frontend:1.2.0

  backend:
    image: 1eshkin/textometr-backend:1.0.1
    environment:
      - MAX_WORKERS=1
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 1000M

  proxy:
    image: staticfloat/nginx-certbot
    ports:
        - 80:80/tcp
        - 443:443/tcp
    environment:
        CERTBOT_EMAIL: alaposhin@gmail.com
    volumes:
      - ./proxy/conf.d:/etc/nginx/user.conf.d:ro
      - ./proxy/letsencrypt:/etc/letsencrypt