version: '3'

services:
  frontend:
    image: 1eshkin/textometr-frontend

  backend:
    image: 1eshkin/textometr-backend
    environment:
      - MAX_WORKERS=1
    deploy:
      resources:
        limits:
          memory: 1000M

  proxy:
    image: staticfloat/nginx-certbot
    ports:
        - 80:80/tcp
        - 443:443/tcp
    environment:
        CERTBOT_EMAIL: alaposhin@gmail.com
    volumes:
      - ./proxy/conf.d:/etc/nginx/user.conf.d:ro
      - ./proxy/letsencrypt:/etc/letsencrypt