FROM python:3.7

COPY ./app /app
COPY ./data /data
COPY ./logs /logs

RUN pip install --no-cache-dir \
  fastapi==0.63.0 \
  uvicorn==0.13.4 \
  numpy==1.19.4 \
  scipy==1.5.4 \
  pandas==1.1.4 \
  nltk==3.5 \
  scikit-learn==0.23.2 \
  pymystem3==0.2.0 \
  joblib==0.17 \
  && python -m nltk.downloader punkt

EXPOSE 8888

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8888", "--debug"]