FROM python:3.7

COPY ./app /app
COPY ./data /data
COPY ./logs /logs
COPY requirements.txt /

RUN pip install --no-cache-dir -r requirements.txt
RUN python -m nltk.downloader punkt

EXPOSE 8888

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8888", "--debug"]