name: Deploy an arbitrary version

on: workflow_dispatch

jobs:
  deploy-docker-images:
    name: Deply Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Deploy to Docker swarm
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: alexey@textometr.ru
          ssh_private_key: ${{ secrets.TEXTOMETR_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.TEXTOMETR_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          keep_files: 5
          deploy_path: /home/alexey/textometr
          stack_file_name: docker-compose.yml
          args: textometr
